# .pre-commit-config.yaml
default_language_version:
  python: python3

repos:   
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        language_version: python3
        
  - repo: local 
    hooks:
      - id: copyright header
        name: Add header copyright to files
        entry: python scripts/copyright.py
        language: python
        files: \.py$