# .pre-commit-config.yaml
default_language_version:
  python: python3

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.9.4'
    hooks:
      - id: ruff
        args: ["--fix"]
        
  - repo: local 
    hooks:
      - id: copyright header
        name: Add header copyright to files
        entry: python scripts/copyright.py
        language: python
        files: \.py$